Signup/in
InnoTableTennis/frontend pull request #29
Opened 2023-07-13 19:20 UTC by n-bor1sov

Sign in + Sign up + error vison fix

2023-07-13 21:46 UTC, KekStroke requested changes
Нужно забрать картинки в лучшем качестве и полном рамере, закинуть их в соответствующие папки с ассетами в $lib/assets. Почистить комменты. Удалить неиспользуемые компоненты.

2023-07-13 21:46 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +	}}>← Back</button
Иконку стрелочки взять с дизайна в фигме

2023-07-13 21:46 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +							<!-- <span class="form-label">Telegram Alias</span> -->
Коментарии лишние убрать

2023-07-13 21:46 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +							<!-- <span class="form-label">Password</span> -->
Убрать коммент лишний

2023-07-13 21:46 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +				<img src="../../../../signin.jpg" alt="" />
signin.jpg переместить в lig/assets и импортировать картинку из $lib/assets

2023-07-13 21:46 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +	@media (max-width: 500px) {
480px

2023-07-13 21:46 UTC, KekStroke commented on src/lib/errorHandler.ts
> +	console.log('hi');
Почистить логи

2023-07-13 21:46 UTC, KekStroke commented on src/lib/errorHandler.ts
> +	console.log('Im there');
Почистить логи

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(main)/+error.svelte
+error.svelte сделать общим. Проверить перед тем как пушить

2023-07-13 21:46 UTC, KekStroke commented on static/signin.jpg
Загрузить картинку в лучшем качестве с яндекс диска

2023-07-13 21:46 UTC, KekStroke commented on static/signup.png
Загрузить картинку в лучшем качестве с яндекс диска

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/+layout.svelte
> +		/* padding: 0 2em; */
Почистить комменты

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +</script>
Почистить комменты

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +	// import Rectangles from '$lib/components/decorations/Rectangles.svelte';
Rectangles.svelte убрать за ненадобностью

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +				<img src="../../../signup.png" alt="Problem with downloading" />
$lib/static

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +	}}>Back →</button
Инонку в svg с фигмы

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +		/* height: 100%; */
Почистить комменты

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +	} */
Почистить

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +	@media (max-height: 500px) {
480px

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +			margin: 7vh 0;
Почему vh?

2023-07-13 21:46 UTC, KekStroke commented on src/routes/(auth)/+layout.svelte
> +</svelte:head>
Вынести в общий layout все, что возможно вынести из обоих layout'ов

2023-07-18 10:54 UTC, KekStroke commented on src/lib/assets/profile-icon-light.jpg
svg иконки нет?

2023-07-18 10:54 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +								bind:this={usernameInput}
Этот бинд не нужен насколько я понимаю

2023-07-18 10:54 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +		width: 15%;
Почему ширина в процентах?

2023-07-18 10:54 UTC, KekStroke commented on src/lib/components/navigation/Login.svelte
> +		height: 10%;
Изменить на rem

2023-07-18 10:54 UTC, KekStroke commented on src/lib/components/navigation/ProfileLink.svelte
> +	} */
```suggestion
```

2023-07-18 10:54 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +			top: 0.5%;
В rem никак?

2023-07-19 08:45 UTC, n-bor1sov commented on src/lib/components/navigation/ProfileLink.svelte
> +	} */
Мне нужна была эта часть для параллельной работы над Profile Link. Буду разделять в разные ветки.

2023-07-19 08:46 UTC, n-bor1sov commented on src/lib/components/navigation/Login.svelte
> +								bind:this={usernameInput}
Без этого не робит ссылка на переход в Sign Up из Sign in

2023-07-19 12:05 UTC, KekStroke requested changes
Убрать белые отступы на страницах, сделать стрелки одинаковой величины. Убрать код для ProfileLink

2023-07-19 12:05 UTC, KekStroke commented on src/lib/components/navigation/ProfileLink.svelte
> +		/* padding: 10%; */
```suggestion
```

2023-07-19 12:05 UTC, KekStroke commented on src/lib/components/navigation/ProfileLink.svelte
> +		/* padding: 10%; */
```suggestion
```

2023-07-19 12:05 UTC, KekStroke commented on src/lib/components/navigation/ProfileLink.svelte
> +	import ProfileIcon from '../icons/ProfileIcon.svelte';
```suggestion
	import ProfileIcon from '$lib/components/icons/ProfileIcon.svelte';
```

2023-07-19 12:05 UTC, KekStroke commented on src/lib/components/navigation/ProfileLink.svelte
> +	$: isMenuVisible;
```suggestion
```
Эта строка ничего не делает

2023-07-19 14:55 UTC, KekStroke commented on src/routes/(auth)/signup/+page.svelte
> +		/* justify-content: center; */
```suggestion
```

2023-07-19 14:55 UTC, KekStroke commented on src/routes/+layout.svelte
> -
добавить слтили в main из гурппы (main)

2023-07-19 14:55 UTC, KekStroke commented on src/routes/+layout.svelte
> -		}
добавить стили в main из гурппы (main) (max-width: 800)

2023-07-19 15:16 UTC, KekStroke approved these changes

2023-07-19 15:16 UTC, merged