Edit mode and filters
InnoTableTennis/frontend pull request #35
Opened 2023-07-14 23:38 UTC by MishaBlin

2023-07-17 22:01 UTC, KekStroke requested changes
Добавить placeholder в фильтер по дате
Фикс фильрра по дате

2023-07-17 22:01 UTC, KekStroke commented on src/routes/tournaments/+page.svelte
> +	// import ToggleCheckboxButton from '$lib/components/base/ToggleCheckboxButton.svelte';
Коммент удалить

2023-07-17 22:01 UTC, KekStroke commented on src/routes/tournaments/+page.svelte
> +<div class="page">
Убрать этот wrapper

2023-07-17 22:01 UTC, KekStroke commented on src/routes/tournaments/+page.svelte
> +	<div class="wrapper">
Придумать более осознанное название класса

2023-07-17 22:01 UTC, KekStroke commented on src/routes/tournaments/+page.svelte
> +		{:else if $userToken}
Вынести логику с проверкой токена общий layout

2023-07-17 22:01 UTC, KekStroke commented on src/routes/tournaments/+page.svelte
> +	}
убрать

2023-07-17 22:01 UTC, KekStroke commented on src/routes/tournaments/+page.svelte
> +		height: 600px;
Не писать в px

2023-07-17 22:01 UTC, KekStroke commented on src/routes/players/+page.svelte
> +		height: 600px;
Поменять px

2023-07-17 22:01 UTC, KekStroke commented on src/routes/players/+page.svelte
> +		{:else if $userToken}
вы нести в layout

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/icons/DescendingIcon.svelte
> +<svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
Сделать width и height через пропы

2023-07-17 22:01 UTC, KekStroke commented on src/lib/stores.ts
> +} from '../lib/types/types';
```suggestion
} from '$lib/types/types';
```

2023-07-17 22:01 UTC, KekStroke commented on src/lib/stores.ts
> +};
вынести в отдельный файл

2023-07-17 22:01 UTC, KekStroke commented on src/lib/types/types.ts
> +}
Вынести в отдельный файл storeTypes.ts или что-то типо такого

2023-07-17 22:01 UTC, KekStroke commented on src/lib/types/types.ts
> +}
Или formStores

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/icons/AscendingIcon.svelte
> +<svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
width, height 100%

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/base/ToggleCheckboxButton.svelte
> +		/* background: var(--main-color); */
Почистить комменты

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/TournamentList.svelte
> +	} */
Это комменты или не комменты? Почистить

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/TournamentList.svelte
> +		<p class="details">Oops! There is not a single entity satisfying the query</p>
Оставить как было и перенести в layout

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterTournamentForm.svelte
> +		console.log(endDateString);
```suggestion
```

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterTournamentForm.svelte
> +			sortBy === 'date' ? 'date' : sortBy === 'kf' ? 'kf' : 'numberOfPlayers';
Убрать, прописать тип в начале

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterTournamentForm.svelte
> +		opacity: 0;
display: hidden

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterPlayerForm.svelte
> +		opacity: 0;
display: hidden

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterPlayerForm.svelte
> +	import { get } from 'svelte/store';
get не нужен, используй везде $

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterPlayerForm.svelte
Переписать всю работу со сторами через $-синтаксис

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterTournamentForm.svelte
Переписать всю работу со сторами через $-синтаксис

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterMatchForm.svelte
> +		opacity: 0;
display:hidden

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/SortFilterMatchForm.svelte
Переписать всю работу со сторами через $-синтаксис

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/PlayersList.svelte
> +		<p class="details">Oops! There is not a single entity satisfying the query</p>
Оставить как было, вынести в отдельный layout

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/AddTournamentForm.svelte
> +		});
Через $ синтаксис

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/AddTournamentForm.svelte
Переписать всю работу со сторами через $-синтаксис

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/AddMatchForm.svelte
Переписать всю работу со сторами через $-синтаксис

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/MatchesList.svelte
> +		console.log(data);
Убрать логи

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/MatchesList.svelte
> +										({match.firstPlayerRatingBefore})
Показывать, даже если delta == 0

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/MatchesList.svelte
> +										({match.firstPlayerRatingBefore})
Это баг, надо пофиксить

2023-07-17 22:01 UTC, KekStroke commented on src/lib/components/base/DropdownInput.svelte
> +	export let inputVal = '';
не должен быть пропом

2023-07-17 22:01 UTC, KekStroke commented on src/routes/+page.svelte
> +<div class="page">
Убрать этот враппер

2023-07-17 22:01 UTC, KekStroke commented on src/routes/+page.svelte
> +	<div class="wrapper">
Переименновать класс

2023-07-17 22:01 UTC, KekStroke commented on src/routes/+page.svelte
> +	}
Это можно убрать

2023-07-17 22:01 UTC, KekStroke commented on src/routes/+page.svelte
> +	$: mode = 'add';
Реактивность не нужна

2023-07-17 22:01 UTC, KekStroke commented on src/routes/+page.svelte
> +	$: chosenId = -1;
Реактивность не нужна

2023-07-17 22:02 UTC, KekStroke requested changes
Добавить placeholder в фильтер по дате

2023-07-18 16:56 UTC, Zaurall commented on src/routes/tournaments/+page.svelte
> +	// import ToggleCheckboxButton from '$lib/components/base/ToggleCheckboxButton.svelte';
-

2023-07-18 16:56 UTC, Zaurall commented on src/routes/tournaments/+page.svelte
> +<div class="page">
done

2023-07-18 16:56 UTC, Zaurall commented on src/routes/tournaments/+page.svelte
> +	<div class="wrapper">
done

2023-07-18 16:56 UTC, Zaurall commented on src/routes/tournaments/+page.svelte
> +		{:else if $userToken}
done

2023-07-18 16:57 UTC, Zaurall commented on src/routes/tournaments/+page.svelte
> +	}
done

2023-07-18 16:58 UTC, Zaurall commented on src/routes/tournaments/+page.svelte
> +		height: 600px;
-

2023-07-18 16:59 UTC, Zaurall commented on src/routes/players/+page.svelte
> +		height: 600px;
to do

2023-07-18 16:59 UTC, Zaurall commented on src/routes/players/+page.svelte
> +		{:else if $userToken}
done

2023-07-18 17:20 UTC, Zaurall commented on src/lib/components/icons/DescendingIcon.svelte
> +<svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2023-07-18 17:21 UTC, Zaurall commented on src/lib/stores.ts
> +} from '../lib/types/types';
done

2023-07-18 17:22 UTC, Zaurall commented on src/lib/stores.ts
> +};
to do

2023-07-18 17:24 UTC, Zaurall commented on src/lib/types/types.ts
> +}
done

2023-07-18 17:32 UTC, Zaurall commented on src/lib/components/icons/AscendingIcon.svelte
> +<svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2023-07-18 17:33 UTC, Zaurall commented on src/lib/components/base/ToggleCheckboxButton.svelte
> +		/* background: var(--main-color); */
done

2023-07-18 17:34 UTC, Zaurall commented on src/lib/components/TournamentList.svelte
> +	} */
done

2023-07-18 17:38 UTC, Zaurall commented on src/lib/components/TournamentList.svelte
> +		<p class="details">Oops! There is not a single entity satisfying the query</p>
done

2023-07-18 17:39 UTC, Zaurall commented on src/lib/components/SortFilterTournamentForm.svelte
> +		console.log(endDateString);
done

2023-07-18 17:41 UTC, Zaurall commented on src/lib/components/SortFilterTournamentForm.svelte
> +			sortBy === 'date' ? 'date' : sortBy === 'kf' ? 'kf' : 'numberOfPlayers';
done

2023-07-18 17:45 UTC, Zaurall commented on src/lib/components/SortFilterTournamentForm.svelte
> +		opacity: 0;
done

2023-07-18 17:45 UTC, Zaurall commented on src/lib/components/SortFilterPlayerForm.svelte
> +		opacity: 0;
done

2023-07-18 17:49 UTC, Zaurall commented on src/lib/components/SortFilterPlayerForm.svelte
> +	import { get } from 'svelte/store';
done?

2023-07-18 17:49 UTC, Zaurall commented on src/lib/components/SortFilterMatchForm.svelte
> +		opacity: 0;
done

2023-07-18 17:50 UTC, Zaurall commented on src/lib/components/SortFilterTournamentForm.svelte
done

2023-07-18 17:50 UTC, Zaurall commented on src/lib/components/SortFilterPlayerForm.svelte
done

2023-07-18 17:50 UTC, Zaurall commented on src/lib/components/SortFilterMatchForm.svelte
done

2023-07-18 17:50 UTC, Zaurall commented on src/routes/+page.svelte
> +<div class="page">
done

2023-07-18 17:50 UTC, Zaurall commented on src/routes/+page.svelte
> +	<div class="wrapper">
done

2023-07-18 17:51 UTC, Zaurall commented on src/routes/+page.svelte
> +	}
done

2023-07-18 17:52 UTC, Zaurall commented on src/routes/+page.svelte
> +	$: mode = 'add';
done

2023-07-18 17:55 UTC, Zaurall commented on src/routes/+page.svelte
> +	$: chosenId = -1;
done

2023-07-19 19:39 UTC, KekStroke reviewed
Переписать на эффективное использование сторов (ниже написано как). Я дальше не стал проверять. Там тоже самое

2023-07-19 19:39 UTC, KekStroke commented on src/lib/components/AddMatchForm.svelte
>  	}
Этот код не будет работать реактивно. Нужно либо переписать объявления по типу
$: firstPlayerName = $AddMatchFormStore.firstPlayerName;
Либо нужно сразу isSubmissionDisabled обновлять по значениям сторов по типу
$: { isSubmissionDisabled != ( $AddmatchFormStore.firstPlayerName & ... )}
Но код дальше написан так, что лучше будет использовать первый вариант

2023-07-19 19:39 UTC, KekStroke commented on src/lib/components/AddMatchForm.svelte
> +	let secondPlayerScore = $AddMatchFormStore.secondPlayerScore;
```suggestion
	$: firstPlayerName = $AddMatchFormStore.firstPlayerName;
	$: secondPlayerName = $AddMatchFormStore.secondPlayerName;
	$: tournamentTitle = $AddMatchFormStore.tournamentTitle;
	$: firstPlayerScore = $AddMatchFormStore.firstPlayerScore;
	$: secondPlayerScore = $AddMatchFormStore.secondPlayerScore;
```

2023-07-19 19:39 UTC, KekStroke commented on src/lib/components/AddMatchForm.svelte
> +		});
```suggestion
		$AddMatchFormStore = {
			firstPlayerName: firstPlayerName,
			secondPlayerName: secondPlayerName,
			tournamentTitle: tournamentTitle,
			firstPlayerScore: firstPlayerScore,
			secondPlayerScore: secondPlayerScore,
		};
```

2023-07-20 13:59 UTC, KekStroke commented on src/lib/types/types.ts
> +	players: number;
playersAmout

2023-07-20 13:59 UTC, KekStroke commented on src/routes/(tournament_player_pages)/tournaments/+page.ts
Переименновать группу в (private)

2023-07-20 13:59 UTC, KekStroke commented on src/lib/components/base/pagination/PaginationBar.svelte
> +		/* margin-bottom: 3em; */
```suggestion
```

2023-07-20 13:59 UTC, KekStroke commented on src/lib/components/base/inputs/InputTemplate.svelte
> +	export let defaultNumValue: number | string = 0;
number | ''

2023-07-20 13:59 UTC, KekStroke commented on src/lib/components/base/OrderButton.svelte
> +	$: value = defaultVal;
```suggestion
```

2023-07-20 13:59 UTC, KekStroke commented on src/lib/components/base/OrderButton.svelte
> +	export let value = false;
```suggestion
	export let value = true;
```

2023-07-20 13:59 UTC, KekStroke commented on src/lib/components/TournamentList.svelte
> +	import PlayersIcon from './icons/PlayersIcon.svelte';
```suggestion
	import PlayersIcon from '$lib/components/icons/PlayersIcon.svelte';
```

2023-07-20 14:28 UTC, Zaurall commented on src/lib/types/types.ts
> +	players: number;
to do

2023-07-20 14:28 UTC, Zaurall commented on src/routes/(tournament_player_pages)/tournaments/+page.ts
done

2023-07-20 14:30 UTC, Zaurall commented on src/lib/components/AddMatchForm.svelte
>  	}
done

2023-07-20 14:30 UTC, Zaurall commented on src/lib/components/AddMatchForm.svelte
> +	let secondPlayerScore = $AddMatchFormStore.secondPlayerScore;
done

2023-07-20 14:30 UTC, Zaurall commented on src/lib/components/AddMatchForm.svelte
> +		});
done

2023-07-20 14:31 UTC, MishaBlin commented on src/routes/(tournament_player_pages)/tournaments/+page.ts
done

2023-07-20 14:32 UTC, MishaBlin commented on src/lib/components/base/pagination/PaginationBar.svelte
> +		/* margin-bottom: 3em; */
done

2023-07-20 14:39 UTC, MishaBlin commented on src/lib/components/TournamentList.svelte
> +	import PlayersIcon from './icons/PlayersIcon.svelte';
done

2023-07-20 14:40 UTC, MishaBlin commented on src/lib/types/types.ts
> +	players: number;
done

2023-07-20 15:19 UTC, Zaurall commented on src/lib/components/base/pagination/PaginationBar.svelte
> +		/* margin-bottom: 3em; */
done

2023-07-20 15:20 UTC, Zaurall commented on src/lib/components/TournamentList.svelte
> +	import PlayersIcon from './icons/PlayersIcon.svelte';
done

2023-07-20 15:20 UTC, Zaurall commented on src/lib/components/base/pagination/PaginationBar.svelte
> +		/* margin-bottom: 3em; */
to do

2023-07-20 15:20 UTC, Zaurall commented on src/lib/components/base/inputs/InputTemplate.svelte
> +	export let defaultNumValue: number | string = 0;
to do

2023-07-20 15:21 UTC, Zaurall commented on src/lib/components/base/OrderButton.svelte
> +	$: value = defaultVal;
to do

2023-07-20 15:29 UTC, Zaurall commented on src/lib/types/types.ts
> +	players: number;
done
no changes

2023-07-20 16:56 UTC, KekStroke requested changes

2023-07-20 16:56 UTC, KekStroke commented on src/lib/components/forms/SortFilterMatchForm.svelte
> +	function updateValue(event: CustomEvent) {
Поменять на updateSortValue или updateRadioGroupValue

2023-07-20 16:56 UTC, KekStroke commented on src/lib/components/forms/SortFilterPlayerForm.svelte
> +	function updateValue(event: CustomEvent) {
Поменять название функции

2023-07-20 16:56 UTC, KekStroke commented on src/lib/components/forms/SortFilterTournamentForm.svelte
> +	function updateValue(event: CustomEvent) {
Поменять название функции

2023-07-20 16:56 UTC, KekStroke commented on src/lib/components/forms/EditMatchForm.svelte
Почему тут нет функций save и reset?

2023-07-20 16:56 UTC, KekStroke commented on src/lib/components/icons/LeftArrow.svelte
> +	export let height = 26;
rem или проценты

2023-07-20 16:56 UTC, KekStroke commented on src/lib/components/icons/RightArrow.svelte
> +	export let height = 26;
rem или проценты

2023-07-20 21:34 UTC, Zaurall commented on src/lib/components/base/OrderButton.svelte
> +	export let value = false;
done

2023-07-20 21:37 UTC, Zaurall commented on src/lib/components/forms/SortFilterMatchForm.svelte
> +	function updateValue(event: CustomEvent) {
done

2023-07-20 21:37 UTC, Zaurall commented on src/lib/components/forms/SortFilterPlayerForm.svelte
> +	function updateValue(event: CustomEvent) {
done

2023-07-20 21:37 UTC, Zaurall commented on src/lib/components/forms/SortFilterTournamentForm.svelte
> +	function updateValue(event: CustomEvent) {
done

2023-07-20 21:41 UTC, Zaurall commented on src/lib/components/icons/LeftArrow.svelte
> +	export let height = 26;
done

2023-07-20 21:41 UTC, Zaurall commented on src/lib/components/icons/RightArrow.svelte
> +	export let height = 26;
done

2023-07-20 22:05 UTC, Zaurall commented on src/lib/components/forms/EditMatchForm.svelte
done

2023-07-21 00:55 UTC, KekStroke approved these changes

2023-07-21 00:56 UTC, merged